import { Group } from 'fabric/fabric-impl';
import { WorkflowState } from '../../interfaces/state-language.interface';
import { PointCoords } from '../../interfaces/point-coords.interface';
import { IDropAreaGroup } from './drop-area.interface';
import { ITiePointCircle } from './tie-point.interface';
import { BranchItems } from '../branch-items.model';
import { IConnectPoint } from './connect-point.interface';

export interface IStateGroup extends Group {
  data: WorkflowState & { stateId: string; parentStateId: string | null; Start: boolean };
  top: number;
  left: number;
  height: number;
  width: number;
  getTop: () => number;
  getLeft: () => number;
  isBranchRoot: () => boolean;
  isMainRoot: () => boolean;
  isInMainBranch: () => boolean;
  alignCenter: () => void;
  shouldHaveTiePoint: () => boolean;
  setBranchItems: (branchItems: BranchItems[]) => void;
  getBranchItems: () => BranchItems[];
  getChildrenStates: () => IStateGroup[];
  getCenterBottomCoordsUnderChildren: (passStateAsFullState?: boolean) => PointCoords;
  getCenterTopCoordsAboveChildren: () => PointCoords;
  getRightMostItemCoordsUnderChildren: (passStateAsFullState?: boolean) => PointCoords;
  getLeftMostItemCoordsUnderChildren: () => PointCoords;
  getCenterTopCoords: () => PointCoords;
  getCenterBottomCoords: () => PointCoords;
  getCenterRightCoords: () => PointCoords;
  getCenterLeftCoords: () => PointCoords;
  cacheCoords(): void;
  getStateData: () => WorkflowState;
  setDropArea: (dropArea: IDropAreaGroup) => void;
  getDropArea: () => IDropAreaGroup;
  getConnectPoint: () => IConnectPoint;
  setConnectPoint: (connectPoint: IConnectPoint) => void;
  setTopTiePoint: (tiePoint: ITiePointCircle) => void;
  getTopTiePoint: () => ITiePointCircle;
  setBottomTiePoint: (tiePoint: ITiePointCircle) => void;
  getBottomTiePoint: () => ITiePointCircle;
  setLeftTiePoint: (tiePoint: ITiePointCircle) => void;
  getLeftTiePoint: () => ITiePointCircle;
  setRightTiePoint: (tiePoint: ITiePointCircle) => void;
  getRightTiePoint: () => ITiePointCircle;
}
